name: audiobooks
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  bloc: ^7.0.0
  flutter_bloc: ^7.0.0
  intl: ^0.17.0
  get: 4.1.4
  flutter: 
    sdk: flutter
  flutter_localizations: 
    sdk: flutter

dev_dependencies: 
  bloc_test: ^8.0.0
  mocktail: ^0.1.0
  very_good_analysis: ^2.1.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  generate: true

