name: audiobooks
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  get: 4.1.4
  flutter: 
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  just_audio: ^0.8.0

dev_dependencies: 
  mocktail: ^0.1.0
  very_good_analysis: ^2.1.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  generate: true

